### ISSUE TITLE
Hide generated address and show "Click here to join meeting", or similar text

### ISSUE THREAD

**Issue by PelleHanses** [shawnchin/jitsi-url-generator#2]
Hi,
how can we change the meeting link to show another text, ex "Click here to join meeting", instead of the long URL? 
I guess I have to change something in jitsi_url_generator.js.

/Pelle

**Comment by shawnchin** [comment]
Anything else I can assist with before I close this issue?

**Comment by PelleHanses** [comment]
Thanks, exactly what I wanted. It solved my question!

`const generator = makeUrlGenerator(function (url) { `
`   $('#url').attr('href', url).text("Click here to join meeting"); `
` }, DEFAULT_DOMAIN, DEFAULT_ROOM_NAME); `

/Pelle

**Comment by shawnchin** [comment]
Awesome. Glad I could help. :)
